{% if cookiecutter.use_docker -%}
services:
  app:
    build:
      context: ../../{{cookiecutter.project_slug}}
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    environment:
      - APP_ENV=local
    volumes:
      - ../../{{cookiecutter.project_slug}}/app:/app/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
{%- endif %}
